version: "3.3"

services:
    app:
        build:
            context: './app'
            dockerfile: Dockerfile
        restart: unless-stopped
    server:
        build:
            context: './server'
            dockerfile: Dockerfile
        restart: unless-stopped
        depends_on:
            - mongo
    mongo:
        image: mongo
    reverse-proxy:
        image: nginx:1.19
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./reverse-proxy/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
            - server
